### PR TITLE
feat: add module hook for devspace app profiles

### PR DESCRIPTION
**Pull request by tmerkel**
## What this PR does / why we need it
Adds a module hook to allow other modules to register devspace app profiles.  See video for scenario.

Video: https://share.getcloudapp.com/nOu1mPJr

## Jira ID

[XX-XX]

### CODE REVIEW

**Comment by jaredallard** [comment]
This is great! Can you add docs as well on how to use this? (see: https://github.com/getoutreach/stencil-golang/blob/main/docs/module-hooks.md)

**Comment by tmerkel** [comment]
@jaredallard OOOOH...docs.  Absolutely!

**Comment by tmerkel** [comment]
@jaredallard Added docs.  I didn't add templates for the `replace|merge` config called out in https://www.devspace.sh/docs/5.x/configuration/profiles/basics ... as I didn't see it used...and didn't seem necessary?  Thoughts on that?

**Review by artemchernyak-outreach — APPROVED** [review]
Looks great, thank you for adding this!

**Pull request merged**
