### PR TITLE
Merge "rc" into "main"

### PR DESCRIPTION
**Pull request by kaldorn**
Approval PR for a manual merge

### CODE REVIEW

**Comment by kaldorn** [comment]
Created with:

# In repo dir
```
git checkout main
git pull
git checkout rc
git pull
gh pr create --head rc --base main -t 'Merge "rc" into "main"' -b "Approval PR for a manual merge"
```

After approval I will run:
```
git checkout main
git merge rc
git push
```

**Comment by kaldorn** [comment]
I have no idea why this is not up to date.

**Comment by jaredallard** [comment]
> Created with:
> 
> In repo dir
> 
> ```
> git checkout main
> git pull
> git checkout rc
> git pull
> gh pr create --head rc --base main -t 'Merge "rc" into "main"' -b "Approval PR for a manual merge"
> ```
> 
> After approval I will run:
> 
> ```
> git checkout main
> git merge rc
> git push
> ```

I _wonder_ who wrote that

**Comment by kaldorn** [comment]
> > Created with:
> > In repo dir
> > ```
> > git checkout main
> > git pull
> > git checkout rc
> > git pull
> > gh pr create --head rc --base main -t 'Merge "rc" into "main"' -b "Approval PR for a manual merge"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After approval I will run:
> > ```
> > git checkout main
> > git merge rc
> > git push
> > ```
> 
> I _wonder_ who wrote that

Jared did. Figured we should bring that along every PR that needs it.

**Pull request merged**
