### PR TITLE
chore: add tags to DD dashboards

### PR DESCRIPTION
**Pull request by pbr0ck3r**
## What this PR does / why we need it
- Add team to DD dashboards

## Jira ID

[XX-XX]

## Notes for your reviewers
-  Depends on first merging https://github.com/getoutreach/monitoring-terraform/pull/1734

### CODE REVIEW

**Review by kaldorn — APPROVED** [review]
That looks reasonable to me.

**Comment by kaldorn** [comment]
Did you validate this?

**Comment by pbr0ck3r** [comment]
Yes, have validated it works. Going to add the `service` tag for monitors as well.

**Comment by pbr0ck3r** [comment]
Closing this out as this has moved to `stencil-outreach`. https://github.com/getoutreach/stencil-outreach/pull/221

**Pull request closed without merging**
