### PR TITLE
fix: remove temporal pods low monitors

### PR DESCRIPTION
**Pull request by bhogatemadhura**
## What this PR does / why we need it
removed the temporal monitor which was using the deprecated variable `available_pods_low_count`

## Jira ID

https://outreach-io.atlassian.net/browse/STAR-1281

### CODE REVIEW

**Comment by jaredallard** [comment]
Considering we removed the monitor that initially added this, I think we should probably remove the correlating temporal one, right? 

Also, should we move [temporal.tf.tpl](https://github.com/getoutreach/stencil-golang/blob/76a6e5dbac0037964f297d421b61cc32528c0295/templates/monitoring/temporal.tf.tpl#L60) into stencil-temporal?

**Comment by bhogatemadhura** [comment]
> Considering we removed the monitor that initially added this, I think we should probably remove the correlating temporal one, right?
> 
> Also, should we move [temporal.tf.tpl](https://github.com/getoutreach/stencil-golang/blob/76a6e5dbac0037964f297d421b61cc32528c0295/templates/monitoring/temporal.tf.tpl#L60) into stencil-temporal?

I'll let @ChrisPRobinson  chime in here

**Comment by ChrisPRobinson** [comment]
@jaredallard ya that's fine with me, I don't really want temporal monitors in this repo anyway

**Comment by ChrisPRobinson** [comment]
I'd rather have them in stencil-temporal but I either missed moving them or moving them was a bit complex so I left them where they were

**Review by george-e-shaw-iv — APPROVED** [review]

**Review by jaredallard — APPROVED** [review]

**Pull request merged**
